### PR TITLE
Remove unnecessary public modifiers and unused imports from interfaces

### PR DESCRIPTION
**Pull request by hansenmc**
- Removed redundant modifiers from interfaces. Interface methods public
and member variables are public static final.
- Removed unused imports

### CODE REVIEW

**Comment by sammefford** [comment]
this PR was merged into develop in 2892242

**Comment by sammefford** [comment]
Darn, we broke javadoc generation with this change.  Some of the imports that we removed were needed for javadocs.  See #476.  I ran all the unit tests to make sure this didn't break those, but next time I need to remember to test javadocs too.

**Comment by kcoleman-marklogic** [comment]
I think we can have our cake and eat it, too, with some javadoc adjustments. I'll investigate.

**Comment by kcoleman-marklogic** [comment]
Here's how you can remove the imports and still make javadoc happy:

For a link to something outside the current package, fully qualify the name. For example, if you remove the import of `javax.xml.bind.DatatypeConverter` from `TemportalDescriptor.java`, then you'd change the javadoc link like this:
```
old: {@link DatatypeConverter#parseDateTime DatatypeConverter.parseDateTime}
new: {@link javax.xml.bind.DatatypeConverter#parseDateTime DatatypeConverter.parseDateTime}
```
Similarly, if you remove the import of `com.marklogic.client.semantics.SPARQLMimeTypes` from `SPARQLResultsHandle.java`, then you'd change the javadoc link like this:
```
old: {@link SPARQLMimeTypes}
new: {@link com.marklogic.client.semantics.SPARQLMimeTypes}
```
This is all covered in glorious (aka exhausting) detail in the discussion of `@see` here:

http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html

**Comment by sammefford** [comment]
Thanks, Kim, good tip!

However, I kinda like using imports for this . . . hope that's not bad . . .

**Pull request closed without merging**
