### PR TITLE
Fix XML serialization in DOMWriter

### PR DESCRIPTION
**Pull request by ryanjdew**
* What issue are you addressing with this pull request?
Complex XML with namespaces were getting serialized incorrectly in the properties. This was found out by trying to write back properties that had extracted text. The root cause seemed to be parameters passed in the wrong order to a few functions. 
* Are you modifying the correct branch? (See CONTRIBUTING.md)
I believe so. This needs to be fixed in both the 3.x and 4.x releases.
* Have you run unit tests? (See CONTRIBUTING.md)
Yes and I've added a unit test to cover this case. I did see some failures, but it appeared to be the same number of failures as before my changes.
* Version of MarkLogic Java Client API (see Readme.txt)
4.0.4 and 3.0.8
* Version of MarkLogic Server (see admin gui on port 8001)
MarkLogic 9.0-6 and 8.0-6
* Java version (`java -version`)
1.8.0_77
* OS and version
MacOS 10.13.6 
* What Changed: What happened before this change? What happens without this change?
XML serialization for the metadata would create invalid XML like below:
    ```xml
    <rapi:metadata xmlns:rapi="http://marklogic.com/rest-api" xmlns:prop="http://marklogic.com/xdmp/property" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <rapi:permissions>
        <rapi:permission>
          <rapi:role-name>rest-writer</rapi:role-name>
          <rapi:capability>update</rapi:capability>
        </rapi:permission>
        <rapi:permission>
          <rapi:role-name>rest-reader</rapi:role-name>
          <rapi:capability>read</rapi:capability>
        </rapi:permission>
      </rapi:permissions>
      <prop:properties>
        <filter:text xmlns:filter="http://marklogic.com/filter">
          <zdef-1006346975:http://www.w3.org/1999/xhtml xmlns:zdef-1593109095="xmlns" xmlns:zdef-1006346975="body" zdef-1593109095:http://www.w3.org/2000/xmlns/="http://www.w3.org/1999/xhtml">
            <zdef-1303289172:http://www.w3.org/1999/xhtml xmlns:zdef-1303289172="p">
              This is a test!</zdef-1303289172:http://www.w3.org/1999/xhtml>
          </zdef-1006346975:http://www.w3.org/1999/xhtml>
        </filter:text>
        <content-type xmlns="http://marklogic.com/filter" xsi:type="xs:string">text/plain</content-type>
        <testId xsi:type="xs:string">123456</testId>
        <size xmlns="http://marklogic.com/filter" xsi:type="xs:string">15</size>
        <filter-capabilities xmlns="http://marklogic.com/filter" xsi:type="xs:string">text</filter-capabilities>
      </prop:properties>
      <rapi:quality>0</rapi:quality>
    </rapi:metadata>
    ```

### CODE REVIEW

**Comment by ehennum** [comment]
@anu3990 , could you review this pull request including the unit tests? Thanks.

**Comment by anu3990** [comment]
"logger" variable is never used in DOMWriter so we can remove lines - 21,22,23 and 38. Same with DocumentMetadataHandleTest, lines 35,36 and 59.

**Comment by ryanjdew** [comment]
logger and corresponding imports have been removed

**Comment by anu3990** [comment]
Thanks Ryan.

**Pull request merged**
