### PR TITLE
Graph delete, Default parameters for query definition

### PR DESCRIPTION
**Pull request by grechaw**
This is a candidate to merge into develop.  It enables some of the Jena work.  The tests and implementation for graph delete are good, and transactions also have some coverage.

The inclusion of new fields on SPARQLQueryDefinition enables the use of some of the important parameters for graph manipulation.  See if you think this PR is good @sammefford @xquery

### CODE REVIEW

**Comment by grechaw** [comment]
I just added in rulesets to this mix.  The ruleset configuration is pretty straightforward, and I don't anticipate any controversy or issue with it.

**Comment by sammefford** [comment]
Thanks Charles!  I merged these into develop and 3.0-develop.  I made minor white-space editing to match the surrounding indentation (using tabs).

**Comment by sammefford** [comment]
The refs for dev are 8dba3ce, 5bea856, and 8fa1c03.  The refs for 3.0-develop are 490b94d, bc2caa8, and 4ac0600.

**Comment by xquery** [comment]
belated +1

**Pull request closed without merging**
