### PR TITLE
Adding test for xdmp.unquote (NODE-109)

### PR DESCRIPTION
**Pull request by anu3990**
So we can incorporate your pull request, please share the following:
* What issue are you addressing with this pull request? https://project.marklogic.com/jira/browse/NODE-109
* Are you modifying the correct branch? (See CONTRIBUTING.md)
* Have you run unit tests? (See CONTRIBUTING.md)
* Version of MarkLogic Java Client API (see Readme.txt)
* Version of MarkLogic Server (see admin gui on port 8001)
* Java version (`java -version`)
* OS and version
* What Changed: What happened before this change? What happens without this change?

### CODE REVIEW

**Review by rjrudin — APPROVED** [review]

**Review by rjrudin — CHANGES_REQUESTED** [review]
@anu3990  Odd, but there are 4 Jenkins failures, not sure why - can you investigate?

**Comment by anu3990** [comment]
I regenerated using the auto-generation. Let's see the run this time.

**Review by rjrudin — APPROVED** [review]
Looks good, I assume these are all code-generated tests?

**Comment by anu3990** [comment]
Yes, these are all code generated using the xdmp-develop brnach.

**Pull request merged**
